# Example configuration file for the chr tool
# Place this at ~/.config/chr.toml to customize values

# The prefix for branch names (default: "ZUP-")
prefix = "ACME-"

# The suffix for production branches (default: "-prd")
suffix_prd = "-prod"

# The suffix for homologation branches (default: "-hml")
suffix_hml = "-hml" 